name: CouponsonaKeyChain
favicon: null
layout_spectrum: 0.86116
typography_spectrum: 0.89406
title: Coupons On A Key Chain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffee27'
    - '#c63b2c'
    - '#06080f'
    - '#9d9f9e'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fvt-IHXyKdgw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dvt-IHXyKdgw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fvt-IHXyKdgw%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Michael Ayton
          url: 'https://www.youtube.com/user/4realValentine'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      description: >-
        Home based franchise business. The worlds only coupon book made to fit
        on your key chain.....Coupons on a Key Chain.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=vt-IHXyKdgw'
      title: Video Franchise Coupons on a Key Chain 720
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Hard Cover book on your key chain
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b81a653-bb73-43e7-b9c2-cfefa41881af.gif
