name: CouponsonaKeyChain
favicon: null
layout_spectrum: 0.79377
typography_spectrum: 0.7909934860654175
title: Coupons On A Key Chain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffee27'
    - '#c63b2c'
    - '#06080f'
    - '#9d9f9e'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
