name: CouponsonaKeyChain
favicon: null
layout_spectrum: 0.359676317544654
typography_spectrum: 0.7909934860654175
title: Coupons On A Key Chain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5604278908576816
  lightness: 0.6768414925318211
  saturation: 0.47311595641076565
  rhythmicContrast: 0.43187166727147996
purpose: []
